name: Conda SageMath CI Pipeline

on: [push, pull_request]

jobs:
  run-conda-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: "3.12.9"

      - name: Configure and update Conda
        run: |
          conda config --set channel_priority strict
          conda config --add channels conda-forge
          conda config --remove channels defaults
          conda update -n base -c defaults conda

      - name: Create environment and install project
        run: |
          conda create -n sage-env python=3.12.9 sagemath gpytorch pytest -y
          conda activate sage-env
          # Dieser Befehl funktioniert auch mit Hatch und löst dein Problem
          pip install -e .
      
      - name: Run tests
        run: |
          conda activate sage-env
          # Führt die Tests ohne Cache aus
          pytest -p no:cache