name: SageMath Tests (Docker)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use SageMath Docker container
        # Lädt das SageMath-Image und mountet dein Repo
        uses: addnab/docker-run-action@v4
        with:
          image: sagemath/sagemath:latest
          options: --user=sage
          run: |
            # Jetzt innerhalb des Containers
            sage -python -m pip install --upgrade pip
            sage -python -m pip install pytest gpytorch torch
            if [ -f requirements.txt ]; then
              sage -python -m pip install -r requirements.txt
            fi
            sage -python -m pytest -v
