name: Test with Sage + PyTorch

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r requirements.txt || true
          pip install pytest gpytorch torch numpy sympy matplotlib

      - name: Run tests
        run: |
          PYTHONPATH=. pytest -v

          