# Ein Name f체r den Workflow, der auf GitHub angezeigt wird
name: SageMath CI/CD Pipeline

# Trigger: Starte den Workflow bei jedem Push und jedem Pull Request
on: [push, pull_request]

jobs:
  # Name des Jobs
  run-sagetests:
    # Betriebssystem, auf dem der Job laufen soll
    runs-on: ubuntu-latest

    # Die einzelnen Schritte, die ausgef체hrt werden
    steps:
      # 1. Schritt: Code aus dem Repository laden
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Schritt: SageMath-Umgebung einrichten (mit der korrekten Version @v2)
      - name: Set up SageMath
        uses: mscroggs/setup-sagemath@v2
        with:
          sage-version: 'latest'

      # 3. Schritt: Zus채tzliche Pakete installieren
      - name: Install dependencies
        run: |
          sage -pip install --upgrade pip
          sage -pip install pytest gpytorch

      # 4. Schritt: Tests mit pytest ausf체hren
      - name: Run tests with pytest
        run: pytest