# Ein Name für den Workflow
name: SageMath Tests

# Trigger: Starte bei jedem Push und Pull Request
on: [push, pull_request]

jobs:
  run-sagetests:
    runs-on: ubuntu-latest
    steps:
      # 1. Code aus dem Repository laden
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. SageMath-Umgebung einrichten
      - name: Set up SageMath
        uses: mscroggs/setup-sagemath@v2
        with:
          sage-version: 'latest'

      # 3. Notwendige Pakete installieren
      - name: Install dependencies
        run: |
          # 🎯 HIER HABE ICH PYTEST UND GPYTORCH HINZUGEFÜGT
          sage -pip install --upgrade pip
          sage -pip install pytest gpytorch

      # 4. Tests mit pytest ausführen
      - name: Run tests with pytest
        run: |
          # 🎯 DA WIR PYTEST INSTALLIERT HABEN, NUTZEN WIR ES AUCH
          pytest