name: SageMath Tests

on: [push, pull_request]

jobs:
  run-sagetests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ SageMath mit Python 3.12.9 einrichten
      - name: Set up SageMath
        uses: mscroggs/setup-sagemath@v2
        with:
          sage-version: '10.4'  # stabile Version mit Python 3.12
          python-version: '3.12.9'

      # 3️⃣ Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          sage -python -m pip install --upgrade pip
          sage -python -m pip install pytest gpytorch torch

          # Optional: requirements.txt installieren
          if [ -f requirements.txt ]; then
            sage -python -m pip install -r requirements.txt
          fi

      # 4️⃣ Tests mit pytest ausführen (innerhalb von Sage)
      - name: Run tests with pytest (via Sage)
        run: |
          sage -python -m pytest -v
