# Ein Name f체r den Workflow
name: Conda SageMath CI Pipeline

# Trigger: Starte bei jedem Push und Pull Request
on: [push, pull_request]

jobs:
  run-conda-tests:
    runs-on: ubuntu-latest
    
    # Standardeinstellung, damit Conda in den Shell-Befehlen funktioniert
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # 1. Schritt: Code aus dem Repository laden
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Schritt: Miniconda-Umgebung einrichten
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: "3.12.9" # Gib hier deine Python-Version an

      # 3. Schritt: Conda-Umgebung erstellen und Abh채ngigkeiten installieren
      - name: Create Conda environment and install dependencies
        run: |
          # Erstellt eine Umgebung namens "sage-env", genau wie bei dir lokal
          # Installiert Python, SageMath, GPyTorch und Pytest vom conda-forge Kanal
          conda create -n sage-env python=3.12.9 sagemath gpytorch pytest -c conda-forge -y
      
      # 4. Schritt: Tests mit pytest ausf체hren
      - name: Run tests
        run: |
          # Aktiviert die gerade erstellte Conda-Umgebung und f체hrt dann pytest aus
          conda activate sage-env
          pytest