name: SageMath Tests (Docker)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests in SageMath container
        uses: addnab/docker-run-action@v3
        with:
          image: sagemath/sagemath:latest
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            # pip updaten und alle benötigten Pakete installieren
            sage -python -m pip install --upgrade pip
            sage -python -m pip install pytest gpytorch torch numpy matplotlib einops sympy scipy

            # Falls du eine requirements.txt hast, lade sie ebenfalls
            if [ -f requirements.txt ]; then
              sage -python -m pip install -r requirements.txt
            fi

            # Tests ausführen
            sage -python -m pytest -v --cache-dir=/home/sage/.pytest_cache
